name: Android
on:
  push:
    branches: dev

jobs:
  Android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ❇️ Setup Nodejs
        uses: actions/setup-node@v3.5.1

      - name: ♨️ Setup Java
        uses: actions/setup-java@v3.7.0
        with:
          java-version: '17'
          distribution: oracle

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🌀 Build Android APK Bundle
        run: |
          eas init --non-interactive --id ${{ secrets.EXPO_PROJECT_ID }}
          eas build --non-interactive --platform android --profile release
