name: Preview
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  preview:
    if: "!contains(github.event.pull_request.labels.*.name, '0 diff dependencies')"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: 🗂️ Setup repo
        uses: actions/checkout@v2

      - name: ❇️ Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Publish to Expo
        run: API_URL=${{ secrets.API_URL }} expo publish --release-channel=pr-${{ github.event.number }} --non-interactive

      - name: 💬 Comment in preview
        uses: expo/expo-github-action/preview-comment@v7
        with:
          channel: pr-${{ github.event.number }}
